name: Continuous Delivery (CD)

on:
  push:
    branches: [ "dev2","main", "master" ]
  workflow_dispatch:

permissions:
  # PENTING: 'write' supaya sistem diizinkan membuat Release baru di halaman depan
  contents: write

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven

    - name: Build application (packaging)
      run: mvn -B package -DskipTests --file pom.xml

    # -------------------------------------------------------------
    # Memunculkan aplikasi di menu 'Releases'
    # -------------------------------------------------------------
    - name: Create Release and Upload JAR
      uses: softprops/action-gh-release@v2
      with:
        tag_name: rilis-v${{ github.run_number }}
        name: Versi Terbaru (Build ${{ github.run_number }})
        files: target/tubes-dpbo-kel4-*.jar